---
# Per environment values which override defaults in hmpps-prisoner-finance-general-ledger-api/values.yaml

generic-service:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi

  ingress:
    host: prisoner-finance-general-ledger-api.hmpps.service.justice.gov.uk

  env:
    JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70.0"
    SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "20"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"

  postgresDatabaseRestore:
    jobName: "hmpps-prisoner-finance-gl-api-postgres-restore"
    enabled: true
    timeout: 3590
    namespace_secrets:
      rds-postgresql-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rds-postgresql-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: prisoner-finance-alerts-prod
